#!/bin/bash
# This script will take an animated GIF and delete every other frame
# Accepts two parameters: input file and output file
# Usage: ./<scriptfilename> input.gif output.gif
# https://gist.github.com/aug2uag/7d19da924715792f4981

# Make a copy of the file
cp "$1" "$2"
if [ -z "$3" ]; then
    frame=2
else
    frame=$3
fi
echo "$frame"
echo "copy completed"
# Get the number of frames
numframes=$(gifsicle "$1" -I | grep -owc "image")
echo "numframes completed"
# Deletion
gifsicle "$1" --unoptimize $(seq -f "#%g" 0 "$frame" "$numframes") -O2 -o "$2"
echo "script completed"
